server:
  port: 15447
shiro:
  plugin-list:
    - me.catand.spdnetserver.plugins.LogPlugin
    - me.catand.spdnetserver.plugins.SPDNetRegisterPlugin
spring:
  datasource:
    url: jdbc:sqlite:SPDNetData.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
