server:
  port: 15447
shiro:
  ws:
    server:
      enable: true
      url: "/ws/shiro"
  plugin-list:
    - me.catand.spdnetserver.plugins.LogPlugin
    - me.catand.spdnetserver.plugins.SPDNetRegisterPlugin
    - me.catand.spdnetserver.plugins.SPDNetGetkeyPlugin
    - me.catand.spdnetserver.plugins.SPDNetOnlinePlugin
    - me.catand.spdnetserver.plugins.SPDNetChangeNamePlugin
spring:
  datasource:
    url: jdbc:sqlite:SPDNetData.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
spd:
  version: 2.5.4
  netVersion: 0.0.1
  motd: 欢迎  :D